name: persona
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/lilay/topgrade/repo/fedora-%OS_VERSION%/lilay-topgrade-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/trixieua/morewaita-icon-theme/repo/fedora-%OS_VERSION%/trixieua-morewaita-icon-theme-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-%OS_VERSION%/ublue-os-packages-fedora-%OS_VERSION%.repo
    install:
      - bazaar
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-drive-menu
      - gnome-shell-extension-gsconnect
      - morewaita-icon-theme
      - topgrade
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software

  - type: fonts
    fonts:
      nerd-fonts:
        - Mononoki

  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - Hot Edge
      - Keep pinned apps in AppGrid

  - type: signing

